### ISSUE TITLE
你好，问下你的时序图用的是什么软件？

### ISSUE THREAD

**Issue by liuywme** [florarose/biji#1]
你好，问下你的时序图用的是什么软件？

**Comment by merryldt** [comment]
Mardown 的写法

**Comment by merryldt** [comment]
Mardown 的写法

在 2019-10-14 20:56:11，"liuyanwen" <notifications@github.com> 写道：


你好，问下你的时序图用的是什么软件？

**Comment by liuywme** [comment]
好的， 谢谢啦
